### ISSUE TITLE
[JOSS] Problem running the example in "Getting Started"

### ISSUE THREAD

**Issue by EmilyBourne** [uit-cosmo/blobmodel#104]
This issue relates to an ongoing reviews at: https://github.com/openjournals/joss-reviews/issues/8032

I am trying to go through the tutorial here:
https://blobmodel.readthedocs.io/en/latest/getting_started.html

but I am seeing unexpected errors. My code is:
```python
import matplotlib.pyplot as plt
from blobmodel import Model

if __name__ == '__main__':
    bm = Model(
        Nx=100,
        Ny=100,
        Lx=10,
        Ly=10,
        dt=0.1,
        T=20,
        periodic_y=True,
        blob_shape="gauss",
        num_blobs=100,
        t_drain=1e10,
        t_init=10,
    )
    print(bm)
    ds = bm.make_realization(file_name="example.nc")

    ds["n"].isel(y=0).mean(dim=("t")).plot()
    plt.show()
```

The output is:
```
2d Blob Model with num_blobs:100 and t_drain:10000000000.0
Summing up Blobs:   0%|                                                                                                                              | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/emily/Code/test/tmp/tmp.py", line 19, in <module>
    ds = bm.make_realization(file_name="example.nc")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emily/Code/venv_blobs/lib/python3.11/site-packages/blobmodel/model.py", line 209, in make_realization
    self._sum_up_blobs(blob, speed_up, error)
  File "/home/emily/Code/venv_blobs/lib/python3.11/site-packages/blobmodel/model.py", line 274, in _sum_up_blobs
    _single_blob = blob.discretize_blob(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emily/Code/venv_blobs/lib/python3.11/site-packages/blobmodel/blobs.py", line 162, in discretize_blob
    self._single_blob(
  File "/home/emily/Code/venv_blobs/lib/python3.11/site-packages/blobmodel/blobs.py", line 240, in _single_blob
    * self._propagation_direction_shape(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emily/Code/venv_blobs/lib/python3.11/site-packages/blobmodel/blobs.py", line 318, in _propagation_direction_shape
    return self.blob_shape.get_blob_shape_prop(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_blob_shape_prop'
```

It seems that the suggested line `blob_shape="gauss",` doesn't match up with the current implementation. Maybe there is a step missing in the tutorial using the `blob_shape` module?

The following code seems to work better:
```python
import matplotlib.pyplot as plt
from blobmodel import Model, BlobShapeImpl, BlobShapeEnum

if __name__ == '__main__':
    bm = Model(
        Nx=100,
        Ny=100,
        Lx=10,
        Ly=10,
        dt=0.1,
        T=20,
        periodic_y=True,
        blob_shape=BlobShapeImpl(BlobShapeEnum.gaussian),
        num_blobs=100,
        t_drain=1e10,
        t_init=10,
    )
    print(bm)
    ds = bm.make_realization(file_name="example.nc")

    ds["n"].isel(y=0).mean(dim=("t")).plot()
    plt.show()
```

**Comment by Sosnowsky** [comment]
I fixed this and all the other docs examples in https://github.com/uit-cosmo/blobmodel/commit/cb57e4109355cfc44b6dfa64b5eb638a659b30ce

Also created a new test suite to test that the doc examples run.

**Comment by Sosnowsky** [comment]
Fixed also the files under examples folder https://github.com/uit-cosmo/blobmodel/commit/9fdf61d1dc3df6990b829bda6e5e620fd5f69d71

**Comment by EmilyBourne** [comment]
I've just noticed that you have put these commits on the `joss` branch. I don't think they affect the contents of the paper even if they are relevant for the review. Usually I wait until such changes are available on the main branch (and can therefore be seen in the docs) before ticking of such items in my review. Merging the doc corrections to the main will also be useful for the other reviewer so he doesn't leave similar issues when he reviews

**Comment by Sosnowsky** [comment]
That's right! I created now a new branch https://github.com/uit-cosmo/blobmodel/tree/docs_update
I cherry-picked the commits mentioned in this issue there and will add some further changes relevant for this issue (mainly I want to find a solution to now repeat the code in the docs, tests and examples, as you mentioned in the commit)

**Comment by Sosnowsky** [comment]
@EmilyBourne I'm done with the updates of the documentation. I am a bit unsure about the procedure now, but is it okay if I ask you to check whether the pull request https://github.com/uit-cosmo/blobmodel/pull/107 addresses this issues (and the other two documentation related issues) before I merge into the main branch?
Thanks!

**Comment by EmilyBourne** [comment]
@Sosnowsky I have had a look. I think this adresses my issues (I am more sure about the other two issues). But it is a bit hard to read in the rst file. I am happy for you to merge and close these issues. I can always reopen or create a new issue if I still cannot run the example

**Comment by Sosnowsky** [comment]
Fixed on https://github.com/uit-cosmo/blobmodel/pull/107
